# Generated by Django 2.1.5 on 2019-01-24 22:58

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='CrtHumano_SPLesteNet',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('leste', models.DecimalField(decimal_places=2, max_digits=5)),
                ('santos', models.DecimalField(decimal_places=2, max_digits=5)),
                ('sao_jose', models.DecimalField(decimal_places=2, max_digits=5)),
                ('data_nota', models.DateField(verbose_name='Data Nota')),
            ],
        ),
        migrations.CreateModel(
            name='CrtHumanoNet',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('capital', models.DecimalField(decimal_places=2, max_digits=5)),
                ('oeste', models.DecimalField(decimal_places=2, max_digits=5)),
                ('centro', models.DecimalField(decimal_places=2, max_digits=5)),
                ('leste', models.DecimalField(decimal_places=2, max_digits=5)),
                ('santos', models.DecimalField(decimal_places=2, max_digits=5)),
                ('sao_jose', models.DecimalField(decimal_places=2, max_digits=5)),
                ('mes', models.CharField(max_length=15)),
            ],
        ),
        migrations.CreateModel(
            name='fotosCrt',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('photo01', models.ImageField(blank=True, null=True, upload_to='imagens')),
                ('photo02', models.ImageField(blank=True, null=True, upload_to='imagens')),
            ],
        ),
    ]
