# Generated by Django 2.1.5 on 2019-01-24 23:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sisID', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='imagemCrt',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('mes', models.CharField(max_length=15)),
                ('photo01', models.ImageField(blank=True, null=True, upload_to='imagens')),
                ('photo02', models.ImageField(blank=True, null=True, upload_to='imagens')),
            ],
        ),
        migrations.DeleteModel(
            name='fotosCrt',
        ),
    ]
