# Generated by Django 2.1.5 on 2019-01-27 01:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sisID', '0010_rreip'),
    ]

    operations = [
        migrations.CreateModel(
            name='dispMovel',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('g2', models.DecimalField(decimal_places=2, max_digits=5)),
                ('g3', models.DecimalField(decimal_places=2, max_digits=5)),
                ('g4', models.DecimalField(decimal_places=2, max_digits=5)),
                ('meta', models.DecimalField(decimal_places=2, max_digits=5)),
                ('mes', models.CharField(max_length=15)),
            ],
        ),
    ]
