# Generated by Django 2.1.5 on 2019-01-27 02:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sisID', '0011_dispmovel'),
    ]

    operations = [
        migrations.CreateModel(
            name='dispMovelCN',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cn12G2', models.DecimalField(decimal_places=2, max_digits=5)),
                ('cn12G3', models.DecimalField(decimal_places=2, max_digits=5)),
                ('cn12G4', models.DecimalField(decimal_places=2, max_digits=5)),
                ('cn13G2', models.DecimalField(decimal_places=2, max_digits=5)),
                ('cn13G3', models.DecimalField(decimal_places=2, max_digits=5)),
                ('cn13G4', models.DecimalField(decimal_places=2, max_digits=5)),
                ('meta', models.DecimalField(decimal_places=2, max_digits=5)),
                ('mes', models.CharField(max_length=15)),
            ],
        ),
    ]
